### ISSUE TITLE
Spring tutorial not working 

### ISSUE THREAD

**Issue by samarpan-rai** [werf/werf-guides#247]
```
minikube version: v1.23.0
K8s version:  v1.22.1

MacOS Darwin 20.6.0 Darwin Kernel Version 20.6.0 RELEASE_X86_64 x86_64
```

The spring [tutorial](https://werf.io/guides/java_springboot/100_basic/30_deploy.html) fails at the moment most likely due to the latest k8s version.

Running the command `werf converge --repo greenspray/werf-guide-app`  causes an error.

```
Error: helm upgrade have failed: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"
```

According to this [issue](https://github.com/kubernetes/kubernetes/issues/90077#issuecomment-718778960), the source of the issue seems to be the Ingress version specified in ingress.yaml file. 

I changed the definition to this:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: werf-guide-app
spec:
  rules:
  - host: werf-guide-app
    http:
      paths:
      - path: /
        backend:
          serviceName: werf-guide-app
          servicePort: 8000
```

However, the issue still persists with the error:

```
Error: helm upgrade have failed: unable to build kubernetes objects from release manifest: error validating
"": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "ser
viceName" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0].ba
ckend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec
.rules[0].http.paths[0]): missing required field "pathType" in io.k8s.api.networking.v1.HTTPIngressPath]
```

I believe the source of the error is coming from deployment.yaml but i am not an expert so wanted to create a new issue here

**Comment by ilya-lesikov** [comment]
To work with K8s v1.22+ Ingress resource should be:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: werf-guide-app
spec:
  rules:
  - host: werf-guide-app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: werf-guide-app
            port:
              number: 8000
```
